In [76]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [77]:
## Load the Dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [78]:
## preprocess the data 
## drop irrelavent features 
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [79]:
##Encode categorical variable 
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [80]:
## Onehot encoder 
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])

In [81]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [82]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [83]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [84]:
## combine all ohe columns with original dataset
data=pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [85]:
## Save the Encoders ans Scaler 
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)


with open('onehot_encoder_geo.pkl',"wb") as file:
        pickle.dump(onehot_encoder_geo,file)

In [86]:
## Divide dataset into independent and dependent feature 
X=data.drop('Exited',axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

##scale the features 
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [87]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [88]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

##ANN Implementation

In [89]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [90]:
(X_train.shape[1],)

(12,)

In [91]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),##HL 1 ## Dense create Hidden layer with 64 hidden neurons and apply activation function also on it 
    Dense(32,activation='relu'), ##HL 2
    Dense(1,activation='sigmoid') #Output layer 
])

In [92]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [93]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [94]:
##Compile the Model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
#set up tensorboard 
log_dir='logs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [96]:
#set up Early stopping 
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [97]:
## train the model Now
history = model.fit(
    X_train,y_train,validation_data = (X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.3956 - accuracy: 0.8359 - val_loss: 0.3635 - val_accuracy: 0.8550
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3566 - accuracy: 0.8541 - val_loss: 0.3644 - val_accuracy: 0.8565
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3486 - accuracy: 0.8572 - val_loss: 0.3510 - val_accuracy: 0.8515
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3437 - accuracy: 0.8574 - val_loss: 0.3456 - val_accuracy: 0.8565
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3391 - accuracy: 0.8608 - val_loss: 0.3366 - val_accuracy: 0.8625
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8600 - val_loss: 0.3471 - val_accuracy: 0.8555
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3383 - accuracy: 0.8624 - val_loss: 0.3564 - val_accuracy: 0.8625
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3352 - accuracy: 0.8637 - val_loss: 0.3514 - val_accuracy: 0.8600
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3302 - accuracy: 0.8616 - val_loss: 0.3413 - val_accuracy: 0.8655
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3311 - accuracy: 0.8630 - val_loss: 0.3445 - val_accuracy: 0.8625

In [98]:
model.save('model.h5')

c:\Users\Chaitanya\OneDrive\Desktop\Deep Learning\ANN Churn Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [99]:
## Load tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [100]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6007 (pid 31624), started 0:04:23 ago. (Use '!kill 31624' to kill it.)

In [ ]:
## load the pickle files